name: Build, test and release

on:
  push:
    branches:
      - develop
      - master

env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  build_test_and_release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release -d

      - name: Build and tag the image for testing and release
        run: >-
          docker build .
          --file Dockerfile
          --tag docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}

      - name: Run tests against the image
        run: >-
          docker run
          --network host
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
          yarn test

      - name: Login to registry
        run: >-
          docker login
          -u ${{ github.actor }}
          -p ${{ secrets.GITHUB_TOKEN }}
          docker.pkg.github.com

      - name: Tag image with release version
        run: >-
          docker tag
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
          docker.pkg.github.com/${IMAGE_NAME}:${{ env.RELEASE_VERSION }}

      - name: Push all tagged images in the repository
        run: >-
          docker push --all-tags
          docker.pkg.github.com/${IMAGE_NAME}
