name: Build, test and release

on:
  push:
    branches:
      - develop
      - master

env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  build_test_and_release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build and tag the image
        run: >-
          docker build .
          --file Dockerfile
          --tag docker.pkg.github.com/${IMAGE_NAME}:to_test

      - name: Run tests against the image
        run: >-
          docker run
          --network host
          docker.pkg.github.com/${IMAGE_NAME}:to_test
          yarn test

      - name: Set release tag
        # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
        run: |
          echo "RELEASE_VERSION=<<EOF" >> $GITHUB_ENV
          $([ ${GITHUB_REF##*/} = "develop" ] && printf '%s\n' $(cat .release_version)-develop ||
          printf '%s\n' $(cat .release_version))" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: ${{ !(github.ref == 'refs/heads/master') }}

      - name: Login to registry
        run: >-
          docker login
          -u ${{ github.actor }}
          -p ${{ secrets.GITHUB_TOKEN }}
          docker.pkg.github.com

      - name: Tag image
        run: >-
          docker tag
          docker.pkg.github.com/${IMAGE_NAME}:to_test
          docker.pkg.github.com/${IMAGE_NAME}:${{ env.RELEASE_VERSION }}

      - name: Push image
        run: >-
          docker push
          docker.pkg.github.com/${IMAGE_NAME}:${{ env.RELEASE_VERSION }}
